/**
 * 50 programmatic SEO landings for /dlya/{slug}.
 * Each entry targets a specific audience / search query in RU.
 * Content is intentionally per-niche (title, seo, outcomes, audience) so pages
 * are not duplicates for Google.
 */
import type { Niche } from '@/lib/niches';
import type { NicheLandingData, NicheLandingFaq } from '@/lib/niche-landing-data';

interface Mk {
  slug: string;            // /dlya/{slug}
  niche: Niche;
  galleryNiche?: Niche;
  badge: string;
  title: string;           // H1 / hero
  seoTitle: string;        // <title>
  description: string;     // hero subtitle
  seoDescription: string;  // meta description
  primaryCta?: string;
  previewTitle: string;
  previewSubtitle: string;
  outcomes: Array<{ title: string; description: string }>;
  audience: string;
  schemaServiceName: string;
  faq?: NicheLandingFaq[];
}

const BASE_FAQ: NicheLandingFaq[] = [
  {
    question: 'Сколько стоит запустить страницу?',
    answer: 'Бесплатно. Создайте страницу, опубликуйте ссылку lnkmx.my/имя и принимайте заявки. Платный тариф нужен только для своего домена и расширенной CRM.',
  },
  {
    question: 'Как клиенты будут оставлять заявки?',
    answer: 'Через форму на странице, WhatsApp, Telegram или прямой звонок. Все обращения попадают в кабинет, уведомления — в Telegram-бот.',
  },
  {
    question: 'Нужно ли уметь делать сайты?',
    answer: 'Нет. AI-онбординг соберёт первую версию страницы по вашему описанию за 2 минуты. Дальше — drag-and-drop редактор на телефоне.',
  },
];

const WORKFLOW_DEFAULT = [
  { title: 'Опишите услугу', description: 'AI подставит шаблон под вашу нишу и сгенерирует первый драфт страницы.' },
  { title: 'Добавьте цены и контакты', description: 'Услуги, прайс, мессенджеры, форма заявки — всё редактируется с телефона.' },
  { title: 'Опубликуйте ссылку', description: 'Ставьте lnkmx.my/имя в Instagram bio, рекламу и Telegram-канал.' },
];

function mk(e: Mk): NicheLandingData {
  return {
    key: e.slug,
    niche: e.niche,
    galleryNiche: e.galleryNiche ?? e.niche,
    canonicalPath: `/dlya/${e.slug}`,
    authFrom: `dlya-${e.slug}`,
    badge: e.badge,
    title: e.title,
    description: e.description,
    seoTitle: e.seoTitle,
    seoDescription: e.seoDescription,
    primaryCta: e.primaryCta ?? 'Создать страницу',
    secondaryCta: 'Посмотреть примеры',
    previewTitle: e.previewTitle,
    previewSubtitle: e.previewSubtitle,
    visualAlt: `Пример страницы — ${e.badge}`,
    stats: [
      { value: '2 мин', label: 'до публикации' },
      { value: '1 ссылка', label: 'для Instagram bio' },
      { value: '0 ₸', label: 'бесплатный старт' },
    ],
    outcomes: e.outcomes,
    workflow: WORKFLOW_DEFAULT,
    faq: e.faq ?? BASE_FAQ,
    schemaServiceName: e.schemaServiceName,
    audience: e.audience,
  };
}

export const NICHE_LANDINGS_50: NicheLandingData[] = [
  // ===== BEAUTY & WELLNESS (12) =====
  mk({
    slug: 'nutritionist', niche: 'health', badge: 'Для диетологов',
    title: 'Сайт диетолога — программы питания, консультации и оплаты',
    seoTitle: 'Сайт диетолога — онлайн-консультации и программы | LinkMAX',
    description: 'Страница диетолога с описанием подхода, программами питания, отзывами клиентов и формой записи на консультацию.',
    seoDescription: 'Создайте сайт диетолога: программы, консультации онлайн, отзывы, оплаты. Заявки сразу в Telegram, бесплатный старт.',
    previewTitle: 'Nutrition by Anna', previewSubtitle: 'Программы · Консультации · Оплаты',
    outcomes: [
      { title: 'Понятные программы', description: 'Месячные планы питания, разовые консультации, ведение — с ценами и форматом.' },
      { title: 'Отзывы и кейсы', description: 'Реальные результаты клиентов с фото «до/после» повышают доверие.' },
      { title: 'Оплата онлайн', description: 'Robokassa и карты — клиент платит сразу со страницы, без созвонов.' },
    ],
    audience: 'Диетологи, нутрициологи, эксперты по питанию',
    schemaServiceName: 'LinkMAX for nutritionists',
  }),
  mk({
    slug: 'yoga-teacher', niche: 'fitness', badge: 'Для йога-преподавателей',
    title: 'Сайт йога-преподавателя — расписание, классы, абонементы',
    seoTitle: 'Сайт йога-преподавателя — расписание и запись | LinkMAX',
    description: 'Соберите страницу йога-инструктора: расписание классов, форматы (онлайн/офлайн), абонементы и форму записи.',
    seoDescription: 'Страница йога-преподавателя с расписанием, абонементами и онлайн-записью. Уведомления о записях в Telegram.',
    previewTitle: 'Yoga with Asel', previewSubtitle: 'Расписание · Классы · Абонементы',
    outcomes: [
      { title: 'Расписание на неделю', description: 'Видимое расписание классов с местом и стилем (хатха, аштанга, инь).' },
      { title: 'Абонементы и разовые', description: 'Покажите тарифы: разовое занятие, 4/8/12 классов в месяц.' },
      { title: 'Запись в один тап', description: 'Кнопка «Записаться» ведёт в WhatsApp/Telegram или форму.' },
    ],
    audience: 'Йога-преподаватели, инструкторы пилатеса, стретчинга',
    schemaServiceName: 'LinkMAX for yoga teachers',
  }),
  mk({
    slug: 'personal-trainer', niche: 'fitness', badge: 'Для персональных тренеров',
    title: 'Сайт персонального тренера — программы, отзывы, заявки',
    seoTitle: 'Сайт персонального тренера — онлайн и офлайн | LinkMAX',
    description: 'Страница тренера: программы тренировок, специализация, кейсы клиентов «до/после», форма заявки.',
    seoDescription: 'Сделайте сайт персонального тренера: программы, кейсы, оплаты и Telegram-уведомления о заявках.',
    previewTitle: 'PT Studio', previewSubtitle: 'Программы · Кейсы · Заявка',
    outcomes: [
      { title: 'Программы по целям', description: 'Похудение, набор массы, реабилитация — с длительностью и ценой.' },
      { title: 'Результаты клиентов', description: 'Фото «до/после», отзывы и видео упражнений.' },
      { title: 'Оплата абонементов', description: 'Пакеты тренировок продаются прямо со страницы.' },
    ],
    audience: 'Персональные фитнес-тренеры, ЛФК-специалисты',
    schemaServiceName: 'LinkMAX for personal trainers',
  }),
  mk({
    slug: 'nail-master', niche: 'beauty', badge: 'Для мастеров маникюра',
    title: 'Сайт мастера маникюра — услуги, портфолио, онлайн-запись',
    seoTitle: 'Сайт мастера маникюра — портфолио и запись | LinkMAX',
    description: 'Страница нейл-мастера: услуги (маникюр, педикюр, дизайн), портфолио работ, цены и онлайн-запись.',
    seoDescription: 'Создайте сайт мастера маникюра: услуги, портфолио, прайс, форма записи. Уведомления в Telegram, ссылка для Instagram.',
    previewTitle: 'Nail Art Studio', previewSubtitle: 'Услуги · Портфолио · Запись',
    outcomes: [
      { title: 'Полное меню услуг', description: 'Аппаратный, классический, педикюр, наращивание — с ценой и длительностью.' },
      { title: 'Портфолио работ', description: 'Галерея дизайнов поднимает чек и снижает количество вопросов.' },
      { title: 'Запись без переписок', description: 'Клиент видит слоты и выбирает удобное время сам.' },
    ],
    audience: 'Мастера маникюра, педикюра, нейл-арта',
    schemaServiceName: 'LinkMAX for nail masters',
  }),
  mk({
    slug: 'lash-master', niche: 'beauty', badge: 'Для лашмейкеров',
    title: 'Сайт лашмейкера — наращивание ресниц, портфолио, запись',
    seoTitle: 'Сайт лашмейкера — портфолио и онлайн-запись | LinkMAX',
    description: 'Страница лашмейкера: эффекты наращивания, фото работ, цены, отзывы и форма записи в одной ссылке.',
    seoDescription: 'Сделайте сайт лашмейкера: эффекты, портфолио, цены, отзывы, онлайн-запись. Telegram-уведомления о заявках.',
    previewTitle: 'Lash Studio', previewSubtitle: 'Эффекты · Портфолио · Запись',
    outcomes: [
      { title: 'Эффекты с примерами', description: 'Классика, 2D, 3D, мега-объём — с фото и стоимостью.' },
      { title: 'Уход и снятие', description: 'Коррекция, снятие, ламинирование — всё на одной странице.' },
      { title: 'Отзывы клиенток', description: 'Социальное доказательство снимает страх «первого раза».' },
    ],
    audience: 'Лашмейкеры, мастера по наращиванию ресниц',
    schemaServiceName: 'LinkMAX for lash artists',
  }),
  mk({
    slug: 'brow-master', niche: 'beauty', badge: 'Для бровистов',
    title: 'Сайт бровиста — оформление, ламинирование, окрашивание',
    seoTitle: 'Сайт бровиста — портфолио бровей и запись | LinkMAX',
    description: 'Страница бровиста: услуги (коррекция, окрашивание, ламинирование), портфолио форм бровей и онлайн-запись.',
    seoDescription: 'Создайте сайт бровиста: услуги, портфолио, цены, запись онлайн. Заявки сразу в Telegram-бот.',
    previewTitle: 'Brow Bar', previewSubtitle: 'Услуги · Формы · Запись',
    outcomes: [
      { title: 'Услуги в одном месте', description: 'Архитектура, ламинирование, окрашивание хной/краской — с ценами.' },
      { title: 'Фото форм бровей', description: 'Портфолио по типам лица — клиент видит результат заранее.' },
      { title: 'Удобная запись', description: 'Свободные слоты и форма заявки прямо со страницы.' },
    ],
    audience: 'Бровисты, мастера архитектуры бровей',
    schemaServiceName: 'LinkMAX for brow artists',
  }),
  mk({
    slug: 'hair-stylist', niche: 'beauty', badge: 'Для парикмахеров-стилистов',
    title: 'Сайт парикмахера-стилиста — стрижки, окрашивание, запись',
    seoTitle: 'Сайт стилиста-парикмахера — портфолио и запись | LinkMAX',
    description: 'Страница парикмахера: услуги (стрижка, окрашивание, уход), портфолио работ, прайс и онлайн-запись.',
    seoDescription: 'Сделайте сайт парикмахера-стилиста: услуги, портфолио, прайс, запись. Сообщения о заявках в Telegram.',
    previewTitle: 'Hair Studio', previewSubtitle: 'Услуги · Портфолио · Запись',
    outcomes: [
      { title: 'Все услуги и цены', description: 'Женские, мужские, детские стрижки, окрашивание, уходы — с прайсом.' },
      { title: 'Портфолио по типам', description: 'Окрашивание airtouch, balayage, shatush — с фото работ.' },
      { title: 'Запись в WhatsApp', description: 'Клиент пишет в мессенджер из карточки услуги одним тапом.' },
    ],
    audience: 'Парикмахеры, стилисты, колористы',
    schemaServiceName: 'LinkMAX for hair stylists',
  }),
  mk({
    slug: 'makeup-artist', niche: 'beauty', badge: 'Для визажистов',
    title: 'Сайт визажиста — образы, выезд, портфолио и заявки',
    seoTitle: 'Сайт визажиста — портфолио и запись на макияж | LinkMAX',
    description: 'Страница визажиста: образы (дневной, вечерний, свадебный), выездной макияж, портфолио, форма заявки.',
    seoDescription: 'Создайте сайт визажиста: услуги, образы, портфолио, форма заявки. Telegram-уведомления, бесплатный старт.',
    previewTitle: 'Makeup by ___', previewSubtitle: 'Образы · Портфолио · Заявка',
    outcomes: [
      { title: 'Прайс по образам', description: 'Дневной, вечерний, свадебный, выездной — с временем работы.' },
      { title: 'Портфолио для выбора', description: 'Галерея образов снимает 80% вопросов до созвона.' },
      { title: 'Бронирование даты', description: 'Форма с датой/локацией ускоряет согласование съёмки.' },
    ],
    audience: 'Визажисты, мастера макияжа, бьюти-стилисты',
    schemaServiceName: 'LinkMAX for makeup artists',
  }),
  mk({
    slug: 'cosmetologist', niche: 'beauty', badge: 'Для косметологов',
    title: 'Сайт косметолога — процедуры, аппараты, запись на консультацию',
    seoTitle: 'Сайт косметолога — процедуры и онлайн-запись | LinkMAX',
    description: 'Страница косметолога: процедуры, аппараты, противопоказания, отзывы и форма записи на консультацию.',
    seoDescription: 'Сделайте сайт косметолога: процедуры, прайс, отзывы, онлайн-запись. Заявки попадают в Telegram-бот.',
    previewTitle: 'Beauty Clinic', previewSubtitle: 'Процедуры · Отзывы · Запись',
    outcomes: [
      { title: 'Каталог процедур', description: 'Чистки, пилинги, инъекции, аппаратные — с описанием и ценой.' },
      { title: 'Доверие к эксперту', description: 'Сертификаты, образование, опыт работы — в одном блоке.' },
      { title: 'Запись на диагностику', description: 'Форма с темой обращения — клиент готовится к консультации.' },
    ],
    audience: 'Косметологи, эстетисты, врачи-дерматологи',
    schemaServiceName: 'LinkMAX for cosmetologists',
  }),
  mk({
    slug: 'massage-therapist', niche: 'health', badge: 'Для массажистов',
    title: 'Сайт массажиста — виды массажа, выезд и онлайн-запись',
    seoTitle: 'Сайт массажиста — виды массажа и запись | LinkMAX',
    description: 'Страница массажиста: виды массажа (классический, спортивный, лимфодренаж), выезд на дом, цены и запись.',
    seoDescription: 'Создайте сайт массажиста: услуги, цены, отзывы, форма записи. Telegram-уведомления, мобильный кабинет.',
    previewTitle: 'Massage Studio', previewSubtitle: 'Виды · Выезд · Запись',
    outcomes: [
      { title: 'Виды массажа с описанием', description: 'Классический, спортивный, лимфодренажный, антицеллюлитный.' },
      { title: 'Кабинет и выезд', description: 'Два формата с разной ценой и зоной выезда.' },
      { title: 'Запись без звонков', description: 'Клиент выбирает дату/время и платит онлайн.' },
    ],
    audience: 'Массажисты, остеопаты, мануальные терапевты',
    schemaServiceName: 'LinkMAX for massage therapists',
  }),
  mk({
    slug: 'tattoo-artist', niche: 'art', badge: 'Для тату-мастеров',
    title: 'Сайт тату-мастера — портфолио, стили, запись на сеанс',
    seoTitle: 'Сайт тату-мастера — портфолио и запись | LinkMAX',
    description: 'Страница тату-мастера: портфолио, стили (минимализм, реализм, олдскул), прайс и форма заявки.',
    seoDescription: 'Сделайте сайт тату-мастера: портфолио, стили, прайс, запись. Заявки сразу в Telegram, ссылка для Instagram bio.',
    previewTitle: 'Tattoo Studio', previewSubtitle: 'Портфолио · Стили · Заявка',
    outcomes: [
      { title: 'Портфолио по стилям', description: 'Графика, реализм, минимализм, цветные — с фото работ.' },
      { title: 'Прайс по площади', description: 'Стоимость за час или за размер — клиент сразу понимает бюджет.' },
      { title: 'Бронь через форму', description: 'Эскиз, площадь, дата — клиент готов к консультации.' },
    ],
    audience: 'Тату-мастера, татуировщики',
    schemaServiceName: 'LinkMAX for tattoo artists',
  }),
  mk({
    slug: 'barber', niche: 'beauty', badge: 'Для барберов',
    title: 'Сайт барбера — стрижки, бороды, онлайн-запись',
    seoTitle: 'Сайт барбера — стрижки и онлайн-запись | LinkMAX',
    description: 'Страница барбера: стрижки, оформление бороды, портфолио, прайс и форма онлайн-записи.',
    seoDescription: 'Создайте сайт барбера: услуги, портфолио, прайс, запись. Telegram-бот для новых заявок, бесплатно.',
    previewTitle: 'Barbershop', previewSubtitle: 'Стрижки · Бороды · Запись',
    outcomes: [
      { title: 'Услуги барбершопа', description: 'Стрижки, бороды, бритьё опасной бритвой — с ценами.' },
      { title: 'Портфолио и стиль', description: 'Фото работ задают эстетику и привлекают «своего» клиента.' },
      { title: 'Запись со ссылки в bio', description: 'Instagram bio ведёт сразу на форму записи.' },
    ],
    audience: 'Барберы, мужские мастера, барбершопы',
    schemaServiceName: 'LinkMAX for barbers',
  }),

  // ===== COACHES & EXPERTS (7) =====
  mk({
    slug: 'business-coach', niche: 'business', badge: 'Для бизнес-коучей',
    title: 'Сайт бизнес-коуча — программы, кейсы, заявка на диагностику',
    seoTitle: 'Сайт бизнес-коуча — программы и кейсы | LinkMAX',
    description: 'Страница бизнес-коуча: ниши, программы, кейсы клиентов, отзывы и форма заявки на диагностическую сессию.',
    seoDescription: 'Сделайте сайт бизнес-коуча: программы, кейсы, отзывы, диагностика. Принимайте оплаты и заявки в одном кабинете.',
    previewTitle: 'Business Coach', previewSubtitle: 'Программы · Кейсы · Заявка',
    outcomes: [
      { title: 'Понятные программы', description: 'Индивидуальный коучинг, групповые программы — длительность и цена.' },
      { title: 'Кейсы с цифрами', description: '«Х→Y за N месяцев» — конкретные результаты вместо абстракций.' },
      { title: 'Диагностика как воронка', description: 'Форма заявки на бесплатную сессию = тёплые лиды.' },
    ],
    audience: 'Бизнес-коучи, ментор-консультанты для предпринимателей',
    schemaServiceName: 'LinkMAX for business coaches',
  }),
  mk({
    slug: 'life-coach', niche: 'expert', badge: 'Для лайф-коучей',
    title: 'Сайт лайф-коуча — направления работы, программы, заявка',
    seoTitle: 'Сайт лайф-коуча — программы и заявка на сессию | LinkMAX',
    description: 'Страница лайф-коуча: направления (отношения, цели, баланс), программы, отзывы и форма заявки.',
    seoDescription: 'Создайте сайт лайф-коуча: направления, программы, отзывы, заявка на сессию. Уведомления в Telegram.',
    previewTitle: 'Life Coach', previewSubtitle: 'Направления · Программы · Заявка',
    outcomes: [
      { title: 'Понятные направления', description: 'Отношения, цели, эмоции — клиент находит «свою» тему.' },
      { title: 'Программы и разовые', description: 'Месячный коучинг, пакеты сессий, разовые встречи — с ценой.' },
      { title: 'Тёплые лиды', description: 'Анкета перед сессией экономит время первой встречи.' },
    ],
    audience: 'Лайф-коучи, коучи личностного роста',
    schemaServiceName: 'LinkMAX for life coaches',
  }),
  mk({
    slug: 'career-coach', niche: 'expert', badge: 'Для карьерных коучей',
    title: 'Сайт карьерного коуча — резюме, собеседования, рост',
    seoTitle: 'Сайт карьерного коуча — программы и заявка | LinkMAX',
    description: 'Страница карьерного коуча: услуги (резюме, LinkedIn, собеседование, рост в найме), кейсы и форма заявки.',
    seoDescription: 'Сделайте сайт карьерного коуча: услуги, кейсы, отзывы, заявка. Оплаты онлайн, CRM по клиентам.',
    previewTitle: 'Career Coach', previewSubtitle: 'Услуги · Кейсы · Заявка',
    outcomes: [
      { title: 'Услуги по этапам', description: 'Аудит резюме, прокачка LinkedIn, mock-интервью, план роста.' },
      { title: 'Кейсы с офферами', description: 'Конкретные истории: «junior → middle», «+40% к окладу».' },
      { title: 'Заявка в один шаг', description: 'Форма с целью клиента — коуч готовится к встрече заранее.' },
    ],
    audience: 'Карьерные консультанты, HR-эксперты, рекрутеры',
    schemaServiceName: 'LinkMAX for career coaches',
  }),
  mk({
    slug: 'financial-advisor', niche: 'business', badge: 'Для финансовых консультантов',
    title: 'Сайт финансового консультанта — услуги, кейсы, заявка',
    seoTitle: 'Сайт финансового консультанта — услуги и заявка | LinkMAX',
    description: 'Страница финансового консультанта: услуги (личный бюджет, инвестиции, налоги), кейсы и форма заявки.',
    seoDescription: 'Создайте сайт финансового консультанта: услуги, кейсы, отзывы, оплаты. Telegram-уведомления о новых заявках.',
    previewTitle: 'Finance Advisor', previewSubtitle: 'Услуги · Кейсы · Заявка',
    outcomes: [
      { title: 'Чёткие услуги', description: 'Финплан, налоги, инвестиции — с описанием и ценой.' },
      { title: 'Кейсы с цифрами', description: 'Конкретные результаты повышают доверие к эксперту.' },
      { title: 'Документы и оплата', description: 'Договор и оплата — прямо со страницы.' },
    ],
    audience: 'Финансовые консультанты, налоговые эксперты',
    schemaServiceName: 'LinkMAX for financial advisors',
  }),
  mk({
    slug: 'nutrition-coach', niche: 'health', badge: 'Для нутрициологов',
    title: 'Сайт нутрициолога — программы, чек-листы, заявки',
    seoTitle: 'Сайт нутрициолога — программы и онлайн-консультации | LinkMAX',
    description: 'Страница нутрициолога: подход, программы, чек-листы, отзывы и форма онлайн-консультации.',
    seoDescription: 'Сделайте сайт нутрициолога: программы, отзывы, оплаты онлайн, заявки в Telegram. Бесплатный старт.',
    previewTitle: 'Nutrition Coach', previewSubtitle: 'Программы · Чек-листы · Заявка',
    outcomes: [
      { title: 'Программы по целям', description: 'Снижение веса, набор массы, ЗОЖ — с длительностью и ценой.' },
      { title: 'Лид-магниты', description: 'Бесплатные чек-листы собирают контакты для будущей рассылки.' },
      { title: 'Онлайн-консультации', description: 'Zoom-ссылка и оплата — на одной странице.' },
    ],
    audience: 'Нутрициологи, специалисты по питанию',
    schemaServiceName: 'LinkMAX for nutrition coaches',
  }),
  mk({
    slug: 'relationship-coach', niche: 'health', badge: 'Для семейных психологов',
    title: 'Сайт семейного психолога — форматы, цены, запись',
    seoTitle: 'Сайт семейного психолога — онлайн-запись | LinkMAX',
    description: 'Страница семейного психолога: форматы (пары, индивидуально, дети), подход, отзывы и форма записи.',
    seoDescription: 'Создайте сайт семейного психолога: услуги, отзывы, онлайн-запись. Уведомления о заявках в Telegram.',
    previewTitle: 'Family Therapy', previewSubtitle: 'Форматы · Подход · Запись',
    outcomes: [
      { title: 'Понятные форматы', description: 'Парная, индивидуальная, детская терапия — с ценой и длительностью.' },
      { title: 'Метод и образование', description: 'Подход (КПТ, EFT) и сертификаты повышают доверие.' },
      { title: 'Деликатная запись', description: 'Форма без лишних полей — клиент чувствует уважение к границам.' },
    ],
    audience: 'Семейные психологи, психотерапевты для пар',
    schemaServiceName: 'LinkMAX for relationship coaches',
  }),
  mk({
    slug: 'mindfulness-coach', niche: 'health', badge: 'Для mindfulness-коучей',
    title: 'Сайт mindfulness-коуча — практики, ретриты, программы',
    seoTitle: 'Сайт mindfulness-коуча — практики и программы | LinkMAX',
    description: 'Страница mindfulness-коуча: практики, групповые программы, ретриты и форма записи на сессию.',
    seoDescription: 'Сделайте сайт mindfulness-коуча: практики, программы, ретриты, оплаты. Telegram-уведомления, бесплатный старт.',
    previewTitle: 'Mindfulness', previewSubtitle: 'Практики · Программы · Запись',
    outcomes: [
      { title: 'Регулярные практики', description: 'Расписание медитаций онлайн с возможностью оплаты участия.' },
      { title: 'Ретриты и интенсивы', description: 'Отдельные страницы под выездные программы и сборы.' },
      { title: 'Подписка на рассылку', description: 'Сбор email для регулярных писем с практиками.' },
    ],
    audience: 'Mindfulness-коучи, преподаватели медитации',
    schemaServiceName: 'LinkMAX for mindfulness coaches',
  }),

  // ===== EDUCATION (6) =====
  mk({
    slug: 'english-tutor', niche: 'education', badge: 'Для репетиторов английского',
    title: 'Сайт репетитора английского — уровни, форматы, запись',
    seoTitle: 'Сайт репетитора английского — расписание и запись | LinkMAX',
    description: 'Страница репетитора английского: уровни (A1–C1), форматы (онлайн/группа/IELTS), цены и запись.',
    seoDescription: 'Создайте сайт репетитора английского: программы, цены, отзывы, онлайн-запись. Оплаты и заявки в одном кабинете.',
    previewTitle: 'English Tutor', previewSubtitle: 'Уровни · Форматы · Запись',
    outcomes: [
      { title: 'Программы по уровням', description: 'A1–C1, разговорный, IELTS/TOEFL — с длительностью и ценой.' },
      { title: 'Отзывы учеников', description: 'Социальное доказательство ускоряет решение родителей и взрослых.' },
      { title: 'Запись на пробный', description: 'Форма пробного урока = главный конвертер.' },
    ],
    audience: 'Репетиторы английского, преподаватели языковых школ',
    schemaServiceName: 'LinkMAX for English tutors',
  }),
  mk({
    slug: 'math-tutor', niche: 'education', badge: 'Для репетиторов математики',
    title: 'Сайт репетитора математики — школа, ОГЭ/ЕГЭ, олимпиады',
    seoTitle: 'Сайт репетитора математики — программы и запись | LinkMAX',
    description: 'Страница репетитора математики: программы (школа, ОГЭ, ЕГЭ, олимпиады), кейсы и форма заявки.',
    seoDescription: 'Сделайте сайт репетитора математики: программы, кейсы, цены, онлайн-запись. Уведомления в Telegram.',
    previewTitle: 'Math Tutor', previewSubtitle: 'Программы · Кейсы · Запись',
    outcomes: [
      { title: 'Программы по целям', description: 'Подтянуть школьную, подготовить к ОГЭ/ЕГЭ, олимпиады.' },
      { title: 'Результаты учеников', description: 'Баллы, поступления, динамика — конкретные кейсы.' },
      { title: 'Пробный урок', description: 'Бесплатная диагностика — основной шаг воронки.' },
    ],
    audience: 'Репетиторы математики, физики, подготовка к экзаменам',
    schemaServiceName: 'LinkMAX for math tutors',
  }),
  mk({
    slug: 'music-teacher', niche: 'music', badge: 'Для преподавателей музыки',
    title: 'Сайт преподавателя музыки — инструменты, уроки, запись',
    seoTitle: 'Сайт преподавателя музыки — уроки и запись | LinkMAX',
    description: 'Страница преподавателя музыки: инструменты, форматы (онлайн/офлайн/группа), прайс и форма записи.',
    seoDescription: 'Создайте сайт преподавателя музыки: инструменты, программы, цены, онлайн-запись. Telegram-уведомления.',
    previewTitle: 'Music Lessons', previewSubtitle: 'Инструменты · Форматы · Запись',
    outcomes: [
      { title: 'Инструменты и стили', description: 'Гитара, фортепиано, вокал — с уровнями и стилями.' },
      { title: 'Видео учеников', description: 'Прогресс учеников в коротких видео = лучший конвертер.' },
      { title: 'Пробный урок', description: 'Форма заявки на знакомство — главный шаг воронки.' },
    ],
    audience: 'Преподаватели музыки, вокала, гитары',
    schemaServiceName: 'LinkMAX for music teachers',
  }),
  mk({
    slug: 'art-teacher', niche: 'art', badge: 'Для преподавателей рисования',
    title: 'Сайт преподавателя рисования — курсы, портфолио, запись',
    seoTitle: 'Сайт преподавателя рисования — курсы и запись | LinkMAX',
    description: 'Страница преподавателя рисования: курсы, мастер-классы, работы учеников и форма записи.',
    seoDescription: 'Сделайте сайт преподавателя рисования: курсы, работы учеников, оплаты, заявки. Telegram-бот для уведомлений.',
    previewTitle: 'Art School', previewSubtitle: 'Курсы · Работы · Запись',
    outcomes: [
      { title: 'Курсы и мастер-классы', description: 'Скетчинг, акварель, академический рисунок — форматы и цены.' },
      { title: 'Работы учеников', description: 'Галерея работ показывает результаты, а не обещания.' },
      { title: 'Запись и оплата', description: 'Клиент бронирует место и платит на странице.' },
    ],
    audience: 'Преподаватели рисования, художественные студии',
    schemaServiceName: 'LinkMAX for art teachers',
  }),
  mk({
    slug: 'online-school', niche: 'education', badge: 'Для онлайн-школ',
    title: 'Сайт онлайн-школы — курсы, преподаватели, запись',
    seoTitle: 'Сайт онлайн-школы — курсы и набор учеников | LinkMAX',
    description: 'Страница онлайн-школы: каталог курсов, преподаватели, отзывы учеников и форма записи.',
    seoDescription: 'Создайте сайт онлайн-школы: курсы, преподаватели, отзывы, оплаты. CRM для учеников в одном кабинете.',
    previewTitle: 'Online School', previewSubtitle: 'Курсы · Преподаватели · Запись',
    outcomes: [
      { title: 'Каталог курсов', description: 'Программы с длительностью, форматом, преподавателем и ценой.' },
      { title: 'Команда школы', description: 'Преподаватели с фото и опытом — повышает доверие.' },
      { title: 'Запись по потокам', description: 'Форма записи с выбором даты старта потока.' },
    ],
    audience: 'Основатели онлайн-школ, методисты, edtech-команды',
    schemaServiceName: 'LinkMAX for online schools',
  }),
  mk({
    slug: 'course-creator', niche: 'education', badge: 'Для авторов онлайн-курсов',
    title: 'Сайт автора онлайн-курса — программа, тарифы, продажи',
    seoTitle: 'Сайт автора онлайн-курса — лендинг и продажи | LinkMAX',
    description: 'Страница автора онлайн-курса: программа, тарифы, отзывы выпускников и форма покупки.',
    seoDescription: 'Сделайте лендинг автора онлайн-курса: программа, тарифы, отзывы, продажи. Оплаты онлайн, CRM учеников.',
    previewTitle: 'Course', previewSubtitle: 'Программа · Тарифы · Покупка',
    outcomes: [
      { title: 'Программа и результат', description: 'Модули, навыки, итоговый результат — структура курса в одном экране.' },
      { title: 'Тарифы с пакетами', description: 'Self-study, с куратором, VIP — разные цены и состав.' },
      { title: 'Продажи онлайн', description: 'Оплата картой/Robokassa прямо со страницы, чек на email.' },
    ],
    audience: 'Авторы онлайн-курсов, эксперты, инфопродюсеры',
    schemaServiceName: 'LinkMAX for course creators',
  }),

  // ===== CREATIVE (7) =====
  mk({
    slug: 'wedding-photographer', niche: 'art', badge: 'Для свадебных фотографов',
    title: 'Сайт свадебного фотографа — пакеты, портфолио, бронирование',
    seoTitle: 'Сайт свадебного фотографа — портфолио и бронирование | LinkMAX',
    description: 'Страница свадебного фотографа: пакеты (от утра жениха до вечеринки), портфолио и форма бронирования даты.',
    seoDescription: 'Создайте сайт свадебного фотографа: пакеты, портфолио, отзывы, бронирование. Telegram-уведомления о заявках.',
    previewTitle: 'Wedding Photographer', previewSubtitle: 'Пакеты · Портфолио · Бронь',
    outcomes: [
      { title: 'Пакеты съёмки', description: 'Утро, ЗАГС, прогулка, банкет — с часами и ценой.' },
      { title: 'Лучшие свадьбы', description: 'Портфолио снимает 80% вопросов до встречи с парой.' },
      { title: 'Бронь даты', description: 'Форма с датой свадьбы и локацией — главный шаг воронки.' },
    ],
    audience: 'Свадебные фотографы',
    schemaServiceName: 'LinkMAX for wedding photographers',
  }),
  mk({
    slug: 'videographer', niche: 'art', badge: 'Для видеографов',
    title: 'Сайт видеографа — работы, форматы съёмки, заявки',
    seoTitle: 'Сайт видеографа — портфолио и заявки | LinkMAX',
    description: 'Страница видеографа: ниши (свадьба, reels, корпоратив), портфолио на YouTube/Vimeo и форма заявки.',
    seoDescription: 'Сделайте сайт видеографа: работы, форматы, цены, заявки. Уведомления в Telegram, мобильный кабинет.',
    previewTitle: 'Videographer', previewSubtitle: 'Работы · Форматы · Заявка',
    outcomes: [
      { title: 'Шоурил и работы', description: 'Видео-блок с YouTube/Vimeo вставкой работает лучше скриншотов.' },
      { title: 'Форматы и пакеты', description: 'Свадьба, reels, корпоратив, продуктовое видео — с ценой.' },
      { title: 'Заявка с датой', description: 'Дата, локация, формат — клиент даёт всё нужное сразу.' },
    ],
    audience: 'Видеографы, видеомонтажёры, режиссёры reels',
    schemaServiceName: 'LinkMAX for videographers',
  }),
  mk({
    slug: 'illustrator', niche: 'art', badge: 'Для иллюстраторов',
    title: 'Сайт иллюстратора — портфолио, услуги, заказы',
    seoTitle: 'Сайт иллюстратора — портфолио и заказы | LinkMAX',
    description: 'Страница иллюстратора: портфолио, услуги (постеры, обложки, стикеры), цены и форма заказа.',
    seoDescription: 'Создайте сайт иллюстратора: портфолио, услуги, цены, форма заказа. Принимайте оплаты и заявки онлайн.',
    previewTitle: 'Illustrator', previewSubtitle: 'Портфолио · Услуги · Заказ',
    outcomes: [
      { title: 'Портфолио по жанрам', description: 'Постеры, обложки, персонажи, стикерпаки — разные галереи.' },
      { title: 'Услуги с ценами', description: 'Прайс по типу работ снимает первый блок «сколько стоит».' },
      { title: 'Бриф через форму', description: 'Заявка с прикреплением референсов экономит часы переписки.' },
    ],
    audience: 'Иллюстраторы, художники, концепт-арт',
    schemaServiceName: 'LinkMAX for illustrators',
  }),
  mk({
    slug: 'dj', niche: 'music', badge: 'Для диджеев',
    title: 'Сайт диджея — миксы, форматы, бронирование',
    seoTitle: 'Сайт диджея — миксы и бронирование | LinkMAX',
    description: 'Страница диджея: миксы (SoundCloud/Mixcloud), форматы (клуб, свадьба, корпоратив) и форма бронирования.',
    seoDescription: 'Сделайте сайт диджея: миксы, форматы, прайс, бронирование. Уведомления о заявках в Telegram.',
    previewTitle: 'DJ', previewSubtitle: 'Миксы · Форматы · Бронь',
    outcomes: [
      { title: 'Миксы в плеере', description: 'SoundCloud/Mixcloud вставка показывает звук, а не описание.' },
      { title: 'Форматы выступлений', description: 'Клуб, свадьба, корпоратив, частная вечеринка — разные цены.' },
      { title: 'Бронь даты', description: 'Форма с датой/местом/райдером — сразу полная заявка.' },
    ],
    audience: 'Диджеи, ведущие, музыкальные продюсеры',
    schemaServiceName: 'LinkMAX for DJs',
  }),
  mk({
    slug: 'musician', niche: 'music', badge: 'Для музыкантов',
    title: 'Сайт музыканта — треки, концерты, мерч',
    seoTitle: 'Сайт музыканта — треки, концерты, мерч | LinkMAX',
    description: 'Страница музыканта: треки на Spotify/Apple Music, расписание концертов, мерч и форма для бронирования.',
    seoDescription: 'Создайте сайт музыканта: треки, концерты, мерч, бронирование. Уведомления в Telegram, бесплатный старт.',
    previewTitle: 'Musician', previewSubtitle: 'Треки · Концерты · Мерч',
    outcomes: [
      { title: 'Треки всех платформ', description: 'Spotify, Apple Music, YouTube — слушают там, где удобно.' },
      { title: 'Расписание концертов', description: 'Список дат с городом и ссылкой на билеты.' },
      { title: 'Мерч и бронь', description: 'Продажа мерча и форма для частных выступлений в одном месте.' },
    ],
    audience: 'Музыканты, группы, певцы',
    schemaServiceName: 'LinkMAX for musicians',
  }),
  mk({
    slug: 'blogger', niche: 'art', badge: 'Для блогеров',
    title: 'Link-in-bio для блогера — соцсети, реклама, PR',
    seoTitle: 'Link-in-bio для блогера — соцсети и реклама | LinkMAX',
    description: 'Страница блогера: соцсети, охваты, прайс на интеграции, кейсы рекламодателей и форма заявки на рекламу.',
    seoDescription: 'Сделайте link-in-bio блогера: соцсети, охваты, прайс на рекламу, заявки. Бесплатно, мобильно, без кода.',
    previewTitle: 'Blogger', previewSubtitle: 'Соцсети · Прайс · Заявка',
    outcomes: [
      { title: 'Все соцсети в одном месте', description: 'Instagram, TikTok, YouTube, Telegram, X — одна ссылка для bio.' },
      { title: 'Медиа-кит с охватами', description: 'Прайс на интеграции, ER, охваты — рекламодатель видит сразу.' },
      { title: 'Заявка на рекламу', description: 'Форма с брендом и бюджетом отсекает нецелевые предложения.' },
    ],
    audience: 'Блогеры, инфлюенсеры, контент-мейкеры',
    schemaServiceName: 'LinkMAX for bloggers',
  }),
  mk({
    slug: 'event-planner', niche: 'events', badge: 'Для организаторов мероприятий',
    title: 'Сайт организатора мероприятий — кейсы, форматы, заявка',
    seoTitle: 'Сайт организатора мероприятий — кейсы и заявка | LinkMAX',
    description: 'Страница ивент-агентства: форматы (свадьбы, корпоративы, дни рождения), кейсы и форма заявки на мероприятие.',
    seoDescription: 'Создайте сайт организатора мероприятий: кейсы, форматы, прайс, заявки. Telegram-уведомления, мобильный CRM.',
    previewTitle: 'Event Agency', previewSubtitle: 'Форматы · Кейсы · Заявка',
    outcomes: [
      { title: 'Форматы мероприятий', description: 'Свадьба, корпоратив, день рождения — разные карточки.' },
      { title: 'Кейсы с фото', description: 'Реализованные проекты задают уровень и формируют ожидания.' },
      { title: 'Заявка с бриф-полями', description: 'Дата, бюджет, гости — сразу полный бриф.' },
    ],
    audience: 'Ивент-менеджеры, организаторы свадеб, корпоративов',
    schemaServiceName: 'LinkMAX for event planners',
  }),

  // ===== BUSINESS / PRO SERVICES (9) =====
  mk({
    slug: 'realtor', niche: 'realestate', badge: 'Для риелторов',
    title: 'Сайт риелтора — объекты, услуги, заявка на показ',
    seoTitle: 'Сайт риелтора — объекты и заявка на показ | LinkMAX',
    description: 'Страница риелтора: услуги (купля, продажа, аренда), объекты, отзывы и форма заявки на показ.',
    seoDescription: 'Сделайте сайт риелтора: услуги, объекты, отзывы, заявка. Уведомления о новых лидах в Telegram-бот.',
    previewTitle: 'Realtor', previewSubtitle: 'Объекты · Услуги · Заявка',
    outcomes: [
      { title: 'Каталог объектов', description: 'Карточки квартир/домов с фото, ценой и характеристиками.' },
      { title: 'Услуги риелтора', description: 'Покупка, продажа, аренда, ипотека — с описанием процесса.' },
      { title: 'Заявка на показ', description: 'Форма с предпочтениями — клиент готов к встрече.' },
    ],
    audience: 'Риелторы, агенты по недвижимости',
    schemaServiceName: 'LinkMAX for realtors',
  }),
  mk({
    slug: 'lawyer', niche: 'business', badge: 'Для юристов',
    title: 'Сайт юриста — практики, кейсы, заявка на консультацию',
    seoTitle: 'Сайт юриста — практики и онлайн-консультация | LinkMAX',
    description: 'Страница юриста: практики (семейное, корпоративное, налоговое), кейсы и форма заявки на консультацию.',
    seoDescription: 'Создайте сайт юриста: практики, кейсы, отзывы, онлайн-консультация. Уведомления о заявках в Telegram.',
    previewTitle: 'Lawyer', previewSubtitle: 'Практики · Кейсы · Заявка',
    outcomes: [
      { title: 'Понятные практики', description: 'Семейное, корпоративное, банкротство, налоги — с описанием.' },
      { title: 'Кейсы и решения', description: 'Реальные дела показывают опыт без раскрытия данных.' },
      { title: 'Платная консультация', description: 'Оплата консультации — отсекает нецелевые обращения.' },
    ],
    audience: 'Юристы, адвокаты, юридические бюро',
    schemaServiceName: 'LinkMAX for lawyers',
  }),
  mk({
    slug: 'notary', niche: 'business', badge: 'Для нотариусов',
    title: 'Сайт нотариуса — услуги, тарифы, запись',
    seoTitle: 'Сайт нотариуса — услуги и запись | LinkMAX',
    description: 'Страница нотариуса: услуги (доверенности, договоры, наследство), тарифы, адрес и форма записи.',
    seoDescription: 'Сделайте сайт нотариуса: услуги, тарифы, адрес, запись онлайн. Уведомления в Telegram, бесплатный старт.',
    previewTitle: 'Notary', previewSubtitle: 'Услуги · Тарифы · Запись',
    outcomes: [
      { title: 'Полный прайс', description: 'Доверенности, договоры, наследственные дела — с тарифами.' },
      { title: 'Адрес и график', description: 'Карта, часы работы, телефон — клиент знает, куда идти.' },
      { title: 'Запись на приём', description: 'Форма с типом услуги ускоряет работу секретаря.' },
    ],
    audience: 'Нотариусы, нотариальные конторы',
    schemaServiceName: 'LinkMAX for notaries',
  }),
  mk({
    slug: 'accountant', niche: 'business', badge: 'Для бухгалтеров',
    title: 'Сайт бухгалтера — услуги, тарифы, заявка',
    seoTitle: 'Сайт бухгалтера — услуги и онлайн-заявка | LinkMAX',
    description: 'Страница бухгалтера: услуги (ИП, ТОО, налоги, отчётность), тарифы, отзывы и форма заявки.',
    seoDescription: 'Создайте сайт бухгалтера: услуги, тарифы, отзывы, заявка. Уведомления в Telegram, CRM для клиентов.',
    previewTitle: 'Accountant', previewSubtitle: 'Услуги · Тарифы · Заявка',
    outcomes: [
      { title: 'Услуги по форме бизнеса', description: 'ИП, ТОО, самозанятые — с тарифами в месяц/квартал.' },
      { title: 'Тарифы пакетами', description: 'Базовый, расширенный, VIP — клиент выбирает по объёму.' },
      { title: 'Документы и оплата', description: 'Договор и оплата — без поездок в офис.' },
    ],
    audience: 'Бухгалтеры на аутсорсе, бухгалтерские бюро',
    schemaServiceName: 'LinkMAX for accountants',
  }),
  mk({
    slug: 'translator', niche: 'services', badge: 'Для переводчиков',
    title: 'Сайт переводчика — языки, тематики, заявка',
    seoTitle: 'Сайт переводчика — языки и заявка | LinkMAX',
    description: 'Страница переводчика: языки, тематики (юр., тех., мед.), стоимость и форма заявки на перевод.',
    seoDescription: 'Сделайте сайт переводчика: языки, тематики, прайс, заявка. Уведомления в Telegram, мобильно.',
    previewTitle: 'Translator', previewSubtitle: 'Языки · Тематики · Заявка',
    outcomes: [
      { title: 'Языковые пары', description: 'EN→RU, KZ→RU, и др. — с указанием носителя/направления.' },
      { title: 'Тематики', description: 'Юридический, технический, медицинский, маркетинг — с примерами.' },
      { title: 'Заявка с файлом', description: 'Форма с прикреплением документа = готовая оценка.' },
    ],
    audience: 'Переводчики, бюро переводов, лингвисты',
    schemaServiceName: 'LinkMAX for translators',
  }),
  mk({
    slug: 'copywriter', niche: 'services', badge: 'Для копирайтеров',
    title: 'Сайт копирайтера — портфолио, услуги, заявка',
    seoTitle: 'Сайт копирайтера — портфолио и заявка | LinkMAX',
    description: 'Страница копирайтера: ниши, портфолио текстов, услуги (статьи, лендинги, рассылки) и форма заявки.',
    seoDescription: 'Создайте сайт копирайтера: портфолио, услуги, цены, заявка. Принимайте оплаты онлайн, мобильный кабинет.',
    previewTitle: 'Copywriter', previewSubtitle: 'Портфолио · Услуги · Заявка',
    outcomes: [
      { title: 'Портфолио и кейсы', description: 'Ссылки на тексты + краткие кейсы «задача → решение → результат».' },
      { title: 'Услуги пакетами', description: 'Статья, лендинг, e-mail рассылка, продающий пост — с ценой.' },
      { title: 'Бриф через форму', description: 'Структурированный бриф экономит часы переписки.' },
    ],
    audience: 'Копирайтеры, контент-маркетологи, редакторы',
    schemaServiceName: 'LinkMAX for copywriters',
  }),
  mk({
    slug: 'smm-manager', niche: 'services', badge: 'Для SMM-менеджеров',
    title: 'Сайт SMM-менеджера — кейсы, услуги, заявка',
    seoTitle: 'Сайт SMM-менеджера — кейсы и заявка | LinkMAX',
    description: 'Страница SMM-специалиста: ниши, кейсы (рост подписчиков и продаж), услуги и форма заявки.',
    seoDescription: 'Сделайте сайт SMM-менеджера: кейсы, услуги, прайс, заявки. Уведомления в Telegram, бесплатный старт.',
    previewTitle: 'SMM', previewSubtitle: 'Кейсы · Услуги · Заявка',
    outcomes: [
      { title: 'Кейсы с цифрами', description: 'Рост подписчиков, ER, продаж — конкретные результаты по клиентам.' },
      { title: 'Услуги и пакеты', description: 'Ведение, упаковка, таргет, reels — с ценой в месяц.' },
      { title: 'Бриф со ссылкой', description: 'Форма с аккаунтом клиента — сразу аудит на руках.' },
    ],
    audience: 'SMM-менеджеры, SMM-агентства',
    schemaServiceName: 'LinkMAX for SMM managers',
  }),
  mk({
    slug: 'marketer', niche: 'business', badge: 'Для маркетологов',
    title: 'Сайт маркетолога — кейсы, услуги, заявка на консультацию',
    seoTitle: 'Сайт маркетолога — кейсы и консультация | LinkMAX',
    description: 'Страница маркетолога: специализация, кейсы (трафик, конверсии, выручка), услуги и форма заявки.',
    seoDescription: 'Создайте сайт маркетолога: кейсы, услуги, цены, консультация. Уведомления о лидах в Telegram-бот.',
    previewTitle: 'Marketer', previewSubtitle: 'Кейсы · Услуги · Заявка',
    outcomes: [
      { title: 'Кейсы по нишам', description: 'B2B, e-com, услуги — с цифрами по трафику и продажам.' },
      { title: 'Услуги с описанием', description: 'Стратегия, performance, аналитика — что входит, сроки.' },
      { title: 'Платная диагностика', description: 'Оплата диагностики отсекает нецелевые заявки.' },
    ],
    audience: 'Маркетологи, performance-специалисты, digital-стратеги',
    schemaServiceName: 'LinkMAX for marketers',
  }),
  mk({
    slug: 'consultant', niche: 'expert', badge: 'Для консультантов',
    title: 'Сайт консультанта — экспертиза, кейсы, заявка',
    seoTitle: 'Сайт консультанта — экспертиза и заявка | LinkMAX',
    description: 'Страница консультанта: экспертиза, кейсы, форматы работы (разовые/проектные) и форма заявки.',
    seoDescription: 'Сделайте сайт консультанта: экспертиза, кейсы, форматы, заявка. Telegram-уведомления, оплаты онлайн.',
    previewTitle: 'Consultant', previewSubtitle: 'Экспертиза · Кейсы · Заявка',
    outcomes: [
      { title: 'Экспертиза в цифрах', description: 'Лет опыта, проектов, ниш — фактуры вместо общих фраз.' },
      { title: 'Кейсы с задачами', description: '«Задача → решение → результат» в одной карточке.' },
      { title: 'Форматы работы', description: 'Разовая консультация, проектное сопровождение, ретейнер.' },
    ],
    audience: 'Консультанты, эксперты в B2B, стратеги',
    schemaServiceName: 'LinkMAX for consultants',
  }),

  // ===== LOCAL SERVICES (9) =====
  mk({
    slug: 'cleaning-service', niche: 'services', badge: 'Для клининговых сервисов',
    title: 'Сайт клининговой службы — услуги, тарифы, заявка',
    seoTitle: 'Сайт клининга — услуги и онлайн-заявка | LinkMAX',
    description: 'Страница клининга: услуги (квартира, офис, после ремонта), тарифы, фото «до/после» и форма заявки.',
    seoDescription: 'Создайте сайт клининга: услуги, тарифы, фото «до/после», онлайн-заявка. Уведомления в Telegram-бот.',
    previewTitle: 'Cleaning Service', previewSubtitle: 'Услуги · Тарифы · Заявка',
    outcomes: [
      { title: 'Виды уборки', description: 'Поддерживающая, генеральная, после ремонта, химчистка — с ценой.' },
      { title: 'До/после в фото', description: 'Фотогалерея результатов = главный конвертер для клиента.' },
      { title: 'Расчёт по адресу', description: 'Форма с площадью и адресом — заявка с готовой оценкой.' },
    ],
    audience: 'Клининговые компании, уборщики на аутсорсе',
    schemaServiceName: 'LinkMAX for cleaning services',
  }),
  mk({
    slug: 'handyman', niche: 'services', badge: 'Для мастеров на час',
    title: 'Сайт мастера на час — услуги, выезд, заявка',
    seoTitle: 'Сайт мастера на час — услуги и выезд | LinkMAX',
    description: 'Страница мастера на час: услуги (сантехника, электрика, мебель), тарифы по часам и форма вызова.',
    seoDescription: 'Сделайте сайт мастера на час: услуги, тарифы, отзывы, заявка. Уведомления в Telegram, бесплатно.',
    previewTitle: 'Handyman', previewSubtitle: 'Услуги · Тарифы · Вызов',
    outcomes: [
      { title: 'Каталог услуг', description: 'Сантехника, электрика, мебель, мелкий ремонт — с ценой работы.' },
      { title: 'Тариф «час мастера»', description: 'Прозрачная стоимость часа + минимальный заказ.' },
      { title: 'Вызов с адресом', description: 'Форма с адресом и описанием — мастер берёт нужные инструменты.' },
    ],
    audience: 'Мастера на час, мелкий бытовой ремонт',
    schemaServiceName: 'LinkMAX for handymen',
  }),
  mk({
    slug: 'car-detailing', niche: 'services', badge: 'Для автодетейлинг-студий',
    title: 'Сайт автодетейлинга — пакеты, портфолио, запись',
    seoTitle: 'Сайт автодетейлинга — пакеты и запись | LinkMAX',
    description: 'Страница детейлинг-студии: пакеты (мойка, химчистка, полировка, керамика), портфолио и онлайн-запись.',
    seoDescription: 'Создайте сайт автодетейлинга: пакеты, портфолио, прайс, онлайн-запись. Уведомления в Telegram.',
    previewTitle: 'Car Detailing', previewSubtitle: 'Пакеты · Портфолио · Запись',
    outcomes: [
      { title: 'Пакеты услуг', description: 'Мойка, химчистка, полировка, керамика — с длительностью и ценой.' },
      { title: 'Фото работ', description: 'До/после на конкретных авто = доверие к мастеру.' },
      { title: 'Запись на удобное время', description: 'Слоты на день — клиент выбирает сам.' },
    ],
    audience: 'Автодетейлинг-студии, автомойки',
    schemaServiceName: 'LinkMAX for car detailing',
  }),
  mk({
    slug: 'florist', niche: 'services', badge: 'Для флористов',
    title: 'Сайт флориста — букеты, доставка, заказ',
    seoTitle: 'Сайт флориста — букеты и доставка | LinkMAX',
    description: 'Страница флориста: каталог букетов, композиции, доставка, цены и форма заказа.',
    seoDescription: 'Сделайте сайт флориста: букеты, доставка, цены, заказы. Уведомления в Telegram, мобильно.',
    previewTitle: 'Florist', previewSubtitle: 'Букеты · Доставка · Заказ',
    outcomes: [
      { title: 'Каталог букетов', description: 'Карточки букетов с фото, ценой, описанием.' },
      { title: 'Зона доставки', description: 'Условия доставки по городу/районам — без созвонов.' },
      { title: 'Заказ в один тап', description: 'Форма с адресом, временем и поздравлением.' },
    ],
    audience: 'Флористы, цветочные магазины',
    schemaServiceName: 'LinkMAX for florists',
  }),
  mk({
    slug: 'catering', niche: 'food', badge: 'Для кейтеринга',
    title: 'Сайт кейтеринга — меню, форматы, заявка',
    seoTitle: 'Сайт кейтеринга — меню и заявка | LinkMAX',
    description: 'Страница кейтеринг-сервиса: меню, форматы (фуршет, банкет, кофе-брейк), кейсы и форма заявки.',
    seoDescription: 'Создайте сайт кейтеринга: меню, форматы, кейсы, заявки. Telegram-уведомления, бесплатный старт.',
    previewTitle: 'Catering', previewSubtitle: 'Меню · Форматы · Заявка',
    outcomes: [
      { title: 'Меню и форматы', description: 'Фуршет, банкет, кофе-брейк — с описанием и ценой на персону.' },
      { title: 'Кейсы и фото столов', description: 'Реальные мероприятия задают уровень и доверие.' },
      { title: 'Бриф для расчёта', description: 'Форма с датой, гостями, бюджетом — расчёт за пару часов.' },
    ],
    audience: 'Кейтеринг-сервисы, корпоративное питание',
    schemaServiceName: 'LinkMAX for catering',
  }),
  mk({
    slug: 'chef', niche: 'food', badge: 'Для частных шефов',
    title: 'Сайт частного шефа — меню, форматы ужинов, бронь',
    seoTitle: 'Сайт частного шефа — меню и бронирование | LinkMAX',
    description: 'Страница частного шефа: форматы ужинов, меню, кейсы и форма бронирования на дату.',
    seoDescription: 'Сделайте сайт частного шефа: меню, форматы, кейсы, бронирование. Уведомления в Telegram.',
    previewTitle: 'Private Chef', previewSubtitle: 'Меню · Форматы · Бронь',
    outcomes: [
      { title: 'Форматы ужинов', description: 'Романтический, дружеский, корпоративный — с числом гостей и ценой.' },
      { title: 'Авторское меню', description: 'Сезонные сеты — клиент видит идею, а не просто список блюд.' },
      { title: 'Бронь даты', description: 'Форма с датой и составом гостей — шеф готовит закупки.' },
    ],
    audience: 'Частные шефы, кулинарные эксперты',
    schemaServiceName: 'LinkMAX for private chefs',
  }),
  mk({
    slug: 'dog-trainer', niche: 'services', badge: 'Для кинологов',
    title: 'Сайт кинолога — программы дрессировки, заявка',
    seoTitle: 'Сайт кинолога — программы и онлайн-запись | LinkMAX',
    description: 'Страница кинолога: программы (ОКД, ЗКС, коррекция поведения), форматы и форма заявки.',
    seoDescription: 'Создайте сайт кинолога: программы, кейсы, цены, заявка. Telegram-уведомления, бесплатно.',
    previewTitle: 'Dog Trainer', previewSubtitle: 'Программы · Кейсы · Заявка',
    outcomes: [
      { title: 'Программы дрессировки', description: 'Щенки, послушание, коррекция, спорт — с длительностью и ценой.' },
      { title: 'Видео-кейсы', description: 'Короткие ролики «до/после» — лучший конвертер для владельцев.' },
      { title: 'Заявка с породой', description: 'Форма с породой, возрастом и запросом — план уже под собаку.' },
    ],
    audience: 'Кинологи, тренеры собак, зоопсихологи',
    schemaServiceName: 'LinkMAX for dog trainers',
  }),
  mk({
    slug: 'interior-designer', niche: 'art', badge: 'Для дизайнеров интерьера',
    title: 'Сайт дизайнера интерьера — проекты, услуги, заявка',
    seoTitle: 'Сайт дизайнера интерьера — портфолио и заявка | LinkMAX',
    description: 'Страница дизайнера интерьера: услуги (планировка, визуализация, авторский надзор), проекты и форма заявки.',
    seoDescription: 'Сделайте сайт дизайнера интерьера: проекты, услуги, прайс, заявка. Уведомления о лидах в Telegram.',
    previewTitle: 'Interior Designer', previewSubtitle: 'Проекты · Услуги · Заявка',
    outcomes: [
      { title: 'Портфолио проектов', description: 'Карточки проектов с превью, площадью и стилем.' },
      { title: 'Услуги по этапам', description: 'Концепция, рабочка, визуализация, надзор — с ценой/м².' },
      { title: 'Заявка с метражом', description: 'Площадь, стиль, бюджет — заявка с готовой оценкой.' },
    ],
    audience: 'Дизайнеры интерьера, архитекторы',
    schemaServiceName: 'LinkMAX for interior designers',
  }),
  mk({
    slug: 'tour-guide', niche: 'travel', badge: 'Для гидов и экскурсоводов',
    title: 'Сайт гида — экскурсии, маршруты, бронирование',
    seoTitle: 'Сайт гида — экскурсии и бронирование | LinkMAX',
    description: 'Страница гида: экскурсии, маршруты, языки, отзывы и форма бронирования с датой.',
    seoDescription: 'Создайте сайт гида: экскурсии, отзывы, цены, бронирование. Уведомления в Telegram, мобильно.',
    previewTitle: 'Tour Guide', previewSubtitle: 'Экскурсии · Отзывы · Бронь',
    outcomes: [
      { title: 'Каталог экскурсий', description: 'Карточки с маршрутом, длительностью, языком и ценой.' },
      { title: 'Отзывы туристов', description: 'Социальное доказательство критично для турпродукта.' },
      { title: 'Бронь с датой', description: 'Форма с датой/гостями/языком — гид планирует день.' },
    ],
    audience: 'Гиды, экскурсоводы, туроператоры',
    schemaServiceName: 'LinkMAX for tour guides',
  }),
];

/** Slug→key map for the catch-all router (`key === slug` here). */
export const NICHE_LANDINGS_50_ROUTE_MAP: Record<string, string> = Object.fromEntries(
  NICHE_LANDINGS_50.map((l) => [l.key, l.key]),
);

/** Flat slug list for sitemap generation. */
export const NICHE_LANDINGS_50_SLUGS: string[] = NICHE_LANDINGS_50.map((l) => l.key);
