import { colors, fonts, radius, shadows, type ColorScheme } from './tokens';

const kebab = (key: string) => key.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

function schemeVars(c: ColorScheme, scheme: 'light' | 'dark'): Array<[string, string]> {
  const vars: Array<[string, string]> = [];
  for (const [key, value] of Object.entries(c)) {
    if (key === 'chart') continue;
    vars.push([`--${kebab(key)}`, value as string]);
  }
  c.chart.forEach((value, i) => vars.push([`--chart-${i + 1}`, value]));

  // Sidebar and bottom navigation sit on raised surfaces in the new system.
  vars.push(
    ['--sidebar', c.card],
    ['--sidebar-background', c.card],
    ['--sidebar-foreground', c.foreground],
    ['--sidebar-primary', c.primary],
    ['--sidebar-primary-foreground', c.primaryForeground],
    ['--sidebar-accent', c.accent],
    ['--sidebar-accent-foreground', c.accentForeground],
    ['--sidebar-border', c.border],
    ['--sidebar-ring', c.ring],
  );

  // Legacy aliases still used by components (glass-*, quiet-bento). They
  // resolve to plain surfaces: no translucency in the app interface.
  vars.push(
    ['--glass-bg', `${c.card} / 0.96`],
    ['--glass-bg-subtle', `${c.card} / 0.86`],
    ['--glass-bg-strong', c.card],
    ['--glass-border', c.border],
    ['--glass-border-subtle', c.border],
    ['--surface-quiet', c.background],
    ['--surface-raised', c.card],
    ['--surface-sunk', c.muted],
    ['--surface-glass', `${c.card} / 0.96`],
    ['--hairline', c.border],
  );

  const sh = shadows(scheme);
  for (const [key, value] of Object.entries(sh)) {
    vars.push([key === 'DEFAULT' ? '--shadow' : `--shadow-${key}`, value]);
  }
  vars.push(
    ['--shadow-soft', sh.sm],
    ['--shadow-lift', sh.lg],
    ['--shadow-glass', sh.md],
    ['--shadow-glass-lg', sh.lg],
    ['--shadow-glass-xl', sh.xl],
  );
  return vars;
}

function block(selector: string, vars: Array<[string, string]>, extra: string[] = []): string {
  const lines = vars.map(([name, value]) => `  ${name}: ${value};`);
  return `${selector} {\n${[...lines, ...extra.map((l) => `  ${l}`)].join('\n')}\n}\n`;
}

/** Variables the app layer defines that the page base must neutralise. */
export const APP_ONLY_VARIABLES = [
  '--shadow-2xs', '--shadow-xs', '--shadow-sm', '--shadow', '--shadow-md',
  '--shadow-lg', '--shadow-xl', '--shadow-2xl', '--font-num',
  '--font-ui', '--font-ui-heading',
  '--button-shadow', '--button-shadow-hover', '--button-shadow-muted', '--button-lift', '--button-radius-compact',
];

export function generateTokensCss(): string {
  const shared: Array<[string, string]> = [
    ['--radius', radius.control],
    ['--radius-control', radius.control],
    ['--radius-card', radius.card],
    ['--radius-sheet', radius.sheet],
    ['--radius-chip', radius.chip],
    ['--font-sans', fonts.sans],
    ['--font-heading', fonts.heading],
    ['--font-num', fonts.num],
    // First family of Tailwind font-sans / font-heading.
    ['--font-ui', "'Onest'"],
    ['--font-ui-heading', "'Onest'"],
    // Buttons in the interface are flat and do not jump on hover.
    ['--button-shadow', '0 1px 2px hsl(216 20% 8% / 0.12)'],
    ['--button-shadow-hover', '0 4px 14px -4px hsl(var(--primary) / 0.45)'],
    ['--button-shadow-muted', '0 1px 2px hsl(216 20% 8% / 0.12)'],
    ['--button-lift', '0px'],
    ['--button-radius-compact', radius.control],
  ];

  return [
    '/* GENERATED by `npm run tokens:build` from src/design-system/tokens.ts. Do not edit. */',
    '/* App interface only: html.lm-app. User pages use the page base in index.css. */',
    '',
    block('html.lm-app', [...shared, ...schemeVars(colors.light, 'light')], ['color-scheme: light;']),
    block('html.lm-app[data-app-theme="dark"]', schemeVars(colors.dark, 'dark'), ['color-scheme: dark;']),
  ].join('\n');
}
