import { build } from "esbuild";
import { loadEnv } from "vite";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

// Generate the MCP function explicitly on every platform. The upstream Vite
// adapter serializes the entire VITE_* environment into the committed bundle;
// this generator deliberately allowlists only the public project URL/ref.

const projectRoot = process.cwd();
const packageJson = JSON.parse(readFileSync(join(projectRoot, "package.json"), "utf8"));
const versions = {
  ...(packageJson.peerDependencies ?? {}),
  ...(packageJson.devDependencies ?? {}),
  ...(packageJson.dependencies ?? {}),
};

function npmSpecifierFor(importPath) {
  const packageName = importPath.startsWith("@")
    ? importPath.split("/").slice(0, 2).join("/")
    : importPath.split("/")[0];
  const subpath = importPath.slice(packageName.length);
  const version = packageName === "@lovable.dev/mcp-js"
    ? "0.23.0"
    : versions[packageName];
  return version ? `npm:${packageName}@${version}${subpath}` : `npm:${importPath}`;
}

const externalizeBareAsNpm = {
  name: "linkmax-mcp-externalize-bare-as-npm",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /.*/ }, ({ path: importPath }) => {
      if (importPath.startsWith(".") || importPath.startsWith("/")) return null;
      if (/^(npm|node|jsr|https?|data):/.test(importPath)) {
        return { path: importPath, external: true };
      }
      return { path: npmSpecifierFor(importPath), external: true };
    });
  },
};

const loadedEnv = loadEnv("production", projectRoot, "VITE_");
const viteEnv = {
  VITE_SUPABASE_PROJECT_ID:
    process.env.VITE_SUPABASE_PROJECT_ID ?? loadedEnv.VITE_SUPABASE_PROJECT_ID,
  VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL ?? loadedEnv.VITE_SUPABASE_URL,
};
const env = {
  // Inline only the values needed to build the OAuth issuer. Never copy the
  // complete process environment (which can contain machine or CI secrets).
  ...(viteEnv.VITE_SUPABASE_PROJECT_ID
    ? { VITE_SUPABASE_PROJECT_ID: viteEnv.VITE_SUPABASE_PROJECT_ID }
    : {}),
  ...(viteEnv.VITE_SUPABASE_URL ? { VITE_SUPABASE_URL: viteEnv.VITE_SUPABASE_URL } : {}),
  MODE: "production",
  BASE_URL: "/",
  DEV: false,
  PROD: true,
  SSR: false,
};

const result = await build({
  stdin: {
    contents:
      'import mcp from "./src/lib/mcp/index.ts";\n' +
      'import { createSupabaseHandler } from "@lovable.dev/mcp-js/stacks/supabase";\n' +
      'Deno.serve(createSupabaseHandler(mcp, { functionName: "mcp" }));\n',
    resolveDir: projectRoot,
    sourcefile: "lovable-mcp-supabase-entry.ts",
    loader: "ts",
  },
  absWorkingDir: projectRoot,
  bundle: true,
  write: false,
  format: "esm",
  platform: "neutral",
  target: "esnext",
  logLevel: "silent",
  define: { "import.meta.env": JSON.stringify(env) },
  plugins: [externalizeBareAsNpm],
});

const generatedPath = join(projectRoot, "supabase", "functions", "mcp", "index.ts");
const banner =
  "// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.\n" +
  "// To take ownership, delete this banner line; the plugin then leaves the file alone.\n" +
  "// supabase function: mcp\n" +
  "// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.\n";

mkdirSync(dirname(generatedPath), { recursive: true });
writeFileSync(generatedPath, banner + (result.outputFiles[0]?.text ?? ""), "utf8");
console.log(`[mcp] Generated ${generatedPath}`);
