// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { AppDatabase } from './extended-types';
import { storage } from '@/lib/storage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  throw new Error('VITE_SUPABASE_URL is required. Create .env from .env.example.');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY is required. Create .env from .env.example.');
}

// Import the supabase client like this:
// import { supabase } from "@/platform/supabase/client";

export const supabase = createClient<AppDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
