// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-my-pages.ts
import { createClient } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_pages_default = defineTool({
  name: "list_my_pages",
  title: "List my LinkMAX pages",
  description: "List all link-in-bio pages that belong to the signed-in LinkMAX user. Returns slug, title, publish status, view count and update time.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of pages to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("pages").select("id, slug, title, is_published, views_count, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { pages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-leads.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_leads_default = defineTool2({
  name: "list_my_leads",
  title: "List my LinkMAX leads",
  description: "List recent leads captured by the signed-in LinkMAX user's pages. Returns contact fields and source page.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Max leads to return. Default 50."),
    page_id: z2.string().uuid().optional().describe("Optional page UUID to filter leads by page.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, page_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("leads").select("id, page_id, form_data, source, status, created_at").eq("owner_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (page_id) query = query.eq("page_id", page_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-analytics-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_analytics_summary_default = defineTool3({
  name: "get_analytics_summary",
  title: "Get analytics summary",
  description: "Return a lightweight analytics summary for the signed-in LinkMAX user: total events, unique visitors and top pages within the given number of days (default 30).",
  inputSchema: {
    days: z3.number().int().min(1).max(365).optional().describe("Look-back window in days. Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const windowDays = days ?? 30;
    const since = new Date(Date.now() - windowDays * 864e5).toISOString();
    const { data: pages, error: pagesErr } = await supabase.from("pages").select("id, slug, title, views_count").eq("user_id", ctx.getUserId());
    if (pagesErr) return { content: [{ type: "text", text: pagesErr.message }], isError: true };
    const pageIds = (pages ?? []).map((p) => p.id);
    if (pageIds.length === 0) {
      return {
        content: [{ type: "text", text: "No pages yet." }],
        structuredContent: { totals: { events: 0, unique_sessions: 0 }, pages: [] }
      };
    }
    const { data: events, error: evErr } = await supabase.from("analytics").select("session_id, page_id, event_type").in("page_id", pageIds).gte("created_at", since);
    if (evErr) return { content: [{ type: "text", text: evErr.message }], isError: true };
    const list = events ?? [];
    const uniq = new Set(list.map((e) => e.session_id).filter(Boolean));
    const byPage = /* @__PURE__ */ new Map();
    for (const e of list) byPage.set(e.page_id, (byPage.get(e.page_id) ?? 0) + 1);
    const top = (pages ?? []).map((p) => ({ slug: p.slug, title: p.title, events: byPage.get(p.id) ?? 0, views_total: p.views_count })).sort((a, b) => b.events - a.events).slice(0, 10);
    return {
      content: [{ type: "text", text: JSON.stringify({ window_days: windowDays, total_events: list.length, unique_sessions: uniq.size, top_pages: top }, null, 2) }],
      structuredContent: { window_days: windowDays, totals: { events: list.length, unique_sessions: uniq.size }, top_pages: top }
    };
  }
});

// src/lib/mcp/tools/create-page.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_page_default = defineTool4({
  name: "create_page",
  title: "Create a new LinkMAX page",
  description: "Create a new link-in-bio page for the signed-in LinkMAX user. Returns the new page id, slug and default settings so the agent can immediately edit blocks and appearance.",
  inputSchema: {
    slug: z4.string().trim().min(1).max(64).optional().describe("Desired URL slug (lowercase). If omitted or already taken, a unique slug is generated."),
    title: z4.string().trim().min(1).max(120).optional().describe("Page title shown in the header and SEO."),
    description: z4.string().trim().max(500).optional().describe("Short page description (SEO/bio).")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ slug, title, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.rpc("mcp_create_user_page", {
      p_slug: slug ?? null,
      p_title: title ?? null,
      p_description: description ?? null
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const row = Array.isArray(data) ? data[0] : data;
    const settings = {
      editable_fields: [
        "title",
        "description",
        "avatar_url",
        "theme_settings",
        "seo_meta",
        "is_published",
        "niche",
        "contact_email",
        "contact_phone",
        "contact_whatsapp"
      ],
      block_types: ["link", "text", "image", "video", "form", "event", "product", "profile", "social"],
      public_url_pattern: "https://lnkmx.my/{slug}"
    };
    return {
      content: [{ type: "text", text: JSON.stringify({ page: row, settings }, null, 2) }],
      structuredContent: { page: row, settings }
    };
  }
});

// src/lib/mcp/tools/get-page-structure.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_page_structure_default = defineTool5({
  name: "get_page_structure",
  title: "Get page structure and blocks",
  description: "Return the full block structure and current configuration of one of the signed-in user's LinkMAX pages, so an agent can review and edit it. Accepts either a page_id (uuid) or a slug.",
  inputSchema: {
    page_id: z5.string().uuid().optional().describe("Page UUID. Provide this OR slug."),
    slug: z5.string().trim().min(1).optional().describe("Page slug. Provide this OR page_id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ page_id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!page_id && !slug) {
      return { content: [{ type: "text", text: "Provide page_id or slug." }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    let pageQuery = supabase.from("pages").select(
      "id, user_id, slug, title, description, avatar_url, avatar_style, theme_settings, seo_meta, is_published, niche, entity_type, contact_email, contact_phone, contact_whatsapp, editor_mode, grid_config, integrations, custom_domain, page_type, updated_at"
    ).eq("user_id", ctx.getUserId()).limit(1);
    pageQuery = page_id ? pageQuery.eq("id", page_id) : pageQuery.eq("slug", slug);
    const { data: pages, error: pageErr } = await pageQuery;
    if (pageErr) return { content: [{ type: "text", text: pageErr.message }], isError: true };
    const page = pages?.[0];
    if (!page) return { content: [{ type: "text", text: "Page not found for this user." }], isError: true };
    const { data: blocks, error: blocksErr } = await supabase.from("blocks").select("id, type, position, title, content, style, is_premium, click_count, schedule").eq("page_id", page.id).order("position", { ascending: true });
    if (blocksErr) return { content: [{ type: "text", text: blocksErr.message }], isError: true };
    const result = { page, blocks: blocks ?? [], block_count: (blocks ?? []).length };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/create-block.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var BLOCK_TYPES = [
  "profile",
  "link",
  "button",
  "text",
  "image",
  "socials",
  "product",
  "video",
  "carousel",
  "custom_code",
  "messenger",
  "form",
  "download",
  "newsletter",
  "testimonial",
  "scratch",
  "map",
  "avatar",
  "separator",
  "catalog",
  "before_after",
  "faq",
  "countdown",
  "pricing",
  "shoutout",
  "booking",
  "community",
  "event"
];
var create_block_default = defineTool6({
  name: "create_block",
  title: "Create a block on a page",
  description: "Create a new block on one of the signed-in LinkMAX user's pages. Supports all block types: link, text, image, button, video, socials, product, form, messenger, map, separator and more. For a link block pass `url` and `title`. The block is appended at the end of the page unless `position` is given. Returns the created block.",
  inputSchema: {
    page_id: z6.string().uuid().describe("UUID of the page to add the block to."),
    type: z6.enum(BLOCK_TYPES).describe("Block type to create."),
    title: z6.string().trim().max(120).optional().describe("Block title (link text, heading, etc)."),
    url: z6.string().url().optional().describe("For link/button/download/video blocks: the target URL."),
    content: z6.record(z6.any()).optional().describe("Full block content object (JSON). All block fields in one place, e.g. { title, url, icon, style, blockStyle, ... }. `page_id`, `type` and `position` are handled separately."),
    position: z6.number().int().min(0).optional().describe("Zero-based position on the page. Defaults to append at the end.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ page_id, type, title, url, content, position }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser6(ctx);
    const { data: pages, error: pageErr } = await supabase.from("pages").select("id").eq("id", page_id).eq("user_id", ctx.getUserId()).limit(1);
    if (pageErr) return { content: [{ type: "text", text: pageErr.message }], isError: true };
    if (!pages?.[0]) {
      return { content: [{ type: "text", text: "Page not found for this user." }], isError: true };
    }
    let nextPosition = position;
    if (nextPosition === undefined) {
      const { data: last, error: posErr } = await supabase.from("blocks").select("position").eq("page_id", page_id).order("position", { ascending: false }).limit(1);
      if (posErr) return { content: [{ type: "text", text: posErr.message }], isError: true };
      nextPosition = (last?.[0]?.position ?? -1) + 1;
    }
    const blockId = crypto.randomUUID();
    const blockContent = {
      id: blockId,
      type,
      ...(content ?? {})
    };
    if (title !== undefined && !(title in blockContent)) blockContent.title = title;
    if (url !== undefined && !(url in blockContent)) blockContent.url = url;
    const { data, error } = await supabase.from("blocks").insert({
      id: blockId,
      page_id,
      type,
      position: nextPosition,
      title: title ?? null,
      content: blockContent,
      style: {},
      is_premium: false
    }).select("id, type, position, title, page_id").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ block: data, content: blockContent, hint: "Use update_block to change its content or style afterwards." }, null, 2)
        }
      ],
      structuredContent: { block: data, content: blockContent }
    };
  }
});

// src/lib/mcp/tools/update-block.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_block_default = defineTool7({
  name: "update_block",
  title: "Update a block's content and design",
  description: "Update the content and/or design (style) of an existing block on one of the signed-in LinkMAX user's pages. Pass `content` with the fields to change (title, url, icon, style, blockStyle, background, etc) and/or `style` for the block's design settings. `title` can be set directly. Returns the updated block.",
  inputSchema: {
    block_id: z7.string().uuid().describe("UUID of the block to update."),
    content: z7.record(z7.any()).optional().describe("Block content fields to merge into the existing content JSON, e.g. { title, url, icon, style, blockStyle }. Omitted fields keep their current value."),
    style: z7.record(z7.any()).optional().describe("Block design settings to merge into the existing style JSON, e.g. { padding, borderRadius, shadow, hoverEffect, animation, background }. Omitted fields keep their current value."),
    title: z7.string().trim().max(120).optional().describe("Optional new block title (also merged into content.title)."),
    position: z7.number().int().min(0).optional().describe("Optional new zero-based position on the page.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ block_id, content, style, title, position }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser7(ctx);
    const { data: existing, error: fetchErr } = await supabase.from("blocks").select("id, type, page_id, content, style, title, position").eq("id", block_id).limit(1);
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    const block = existing?.[0];
    if (!block) return { content: [{ type: "text", text: "Block not found." }], isError: true };
    const { data: pageCheck, error: pageErr } = await supabase.from("pages").select("id").eq("id", block.page_id).eq("user_id", ctx.getUserId()).limit(1);
    if (pageErr) return { content: [{ type: "text", text: pageErr.message }], isError: true };
    if (!pageCheck?.[0]) {
      return { content: [{ type: "text", text: "Block does not belong to a page owned by this user." }], isError: true };
    }
    const mergedContent = { ...(block.content ?? {}), ...(content ?? {}) };
    if (title !== undefined) mergedContent.title = title;
    const update = {
      content: mergedContent,
      style: { ...(block.style ?? {}), ...(style ?? {}) }
    };
    if (title !== undefined) update.title = title;
    if (position !== undefined) update.position = position;
    const { data, error } = await supabase.from("blocks").update(update).eq("id", block_id).select("id, type, page_id, position, title, content, style").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ block: data }, null, 2) }],
      structuredContent: { block: data }
    };
  }
});

// src/lib/mcp/tools/update-page.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@2.95.3";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@3.25.76";
function supabaseForUser8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_page_default = defineTool8({
  name: "update_page",
  title: "Update a page's design and settings",
  description: "Update the appearance and settings of one of the signed-in LinkMAX user's pages: title, description, avatar, theme (theme_settings), SEO meta, publish state. Pass only the fields to change. Returns the updated page.",
  inputSchema: {
    page_id: z8.string().uuid().describe("UUID of the page to update."),
    title: z8.string().trim().max(120).optional().describe("New page title shown in header and SEO."),
    description: z8.string().trim().max(500).optional().describe("New page description (SEO/bio)."),
    avatar_url: z8.string().url().optional().describe("New avatar image URL."),
    is_published: z8.boolean().optional().describe("Set true to publish the page, false to unpublish."),
    theme_settings: z8.record(z8.any()).optional().describe("Page theme/design settings to merge, e.g. { background, font, accent, layout, spacing }. Omitted keys keep current values."),
    seo_meta: z8.record(z8.any()).optional().describe("SEO meta object to merge, e.g. { title, description, ogImage }.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ page_id, title, description, avatar_url, is_published, theme_settings, seo_meta }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser8(ctx);
    const { data: existing, error: fetchErr } = await supabase.from("pages").select("id, theme_settings, seo_meta").eq("id", page_id).eq("user_id", ctx.getUserId()).limit(1);
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing?.[0]) {
      return { content: [{ type: "text", text: "Page not found for this user." }], isError: true };
    }
    const update = {};
    if (title !== undefined) update.title = title;
    if (description !== undefined) update.description = description;
    if (avatar_url !== undefined) update.avatar_url = avatar_url;
    if (is_published !== undefined) update.is_published = is_published;
    if (theme_settings !== undefined) {
      update.theme_settings = { ...(existing[0].theme_settings ?? {}), ...theme_settings };
    }
    if (seo_meta !== undefined) {
      update.seo_meta = { ...(existing[0].seo_meta ?? {}), ...seo_meta };
    }
    const { data, error } = await supabase.from("pages").update(update).eq("id", page_id).select("id, slug, title, description, is_published, theme_settings, updated_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ page: data }, null, 2) }],
      structuredContent: { page: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pphdcfxucfndmwulpfwv";
var mcp_default = defineMcp({
  name: "linkmax-mcp",
  title: "LinkMAX MCP",
  version: "0.1.0",
  instructions: "Tools for LinkMAX \u2014 a link-in-bio and micro-business OS. Use `list_my_pages` to browse the user's published pages, `get_page_structure` to inspect a page's blocks, `create_page` to make a new page, `create_block` to add blocks (including links), `update_block` to change block content and design, `update_page` to change the page theme and publish state, `list_my_leads` to read captured leads, and `get_analytics_summary` for a quick performance overview. All tools operate on the signed-in user's own data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_pages_default, list_my_leads_default, get_analytics_summary_default, create_page_default, get_page_structure_default, create_block_default, update_block_default, update_page_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
