// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: (key: string) => globalThis.localStorage?.getItem(key) ?? null,
      setItem: (key: string, value: string) => globalThis.localStorage?.setItem(key, value),
      removeItem: (key: string) => globalThis.localStorage?.removeItem(key),
    },
    persistSession: true,
    autoRefreshToken: true,
  }
});
